//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Dynamics.Dynamics365Bot.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Dynamics.Dynamics365Bot.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I didn&apos;t understand you. I am still learning..
        /// </summary>
        internal static string CannotUnderstand {
            get {
                return ResourceManager.GetString("CannotUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to perform this action. Contact your administrator for further help..
        /// </summary>
        internal static string ForbiddenError {
            get {
                return ResourceManager.GetString("ForbiddenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again later. If you see this message again, contact your administrator..
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Case By Ticket Number; Search Case Using Relevance Search.
        /// </summary>
        internal static string Help_Functionality {
            get {
                return ResourceManager.GetString("Help_Functionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can help you with following.
        /// </summary>
        internal static string Help_Message {
            get {
                return ResourceManager.GetString("Help_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow the case.
        /// </summary>
        internal static string SeachCase_FollowOption {
            get {
                return ResourceManager.GetString("SeachCase_FollowOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send mail to the case.
        /// </summary>
        internal static string SearchCase_EmailOption {
            get {
                return ResourceManager.GetString("SearchCase_EmailOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nope, nothing for now.
        /// </summary>
        internal static string SearchCase_NoOption {
            get {
                return ResourceManager.GetString("SearchCase_NoOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result found..
        /// </summary>
        internal static string SearchCase_NoResultFound {
            get {
                return ResourceManager.GetString("SearchCase_NoResultFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to.
        /// </summary>
        internal static string SearchCase_OptionsText {
            get {
                return ResourceManager.GetString("SearchCase_OptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulling up the entity you selected....
        /// </summary>
        internal static string SearchCase_ProcessingEntity {
            get {
                return ResourceManager.GetString("SearchCase_ProcessingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevance Search is not enabled. Kindly check with your administrator..
        /// </summary>
        internal static string SearchCase_RelevanceSearchDisabled {
            get {
                return ResourceManager.GetString("SearchCase_RelevanceSearchDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Related Records.
        /// </summary>
        internal static string SearchCase_ShowRelatedRecords {
            get {
                return ResourceManager.GetString("SearchCase_ShowRelatedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter case number/ticket number..
        /// </summary>
        internal static string SearchCase_Start {
            get {
                return ResourceManager.GetString("SearchCase_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login may have expired. Try sending the message again..
        /// </summary>
        internal static string UnauthorizedError {
            get {
                return ResourceManager.GetString("UnauthorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! I am Dynamics 365 Bot..
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
